version: '3'
services:
  directus:
    image: directus/directus:10
    network_mode: host
    # ports:
    #   - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./snapshots:/directus/snapshots
    env_file:
      - .env
    environment:
      DB_CLIENT: 'mysql'
      DB_HOST: 'localhost'
      DB_PORT: 3306
      DB_DATABASE: ${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}

      AUTH_PROVIDERS: 'github'
      AUTH_GITHUB_DRIVER: 'oauth2'
      AUTH_GITHUB_AUTHORIZE_URL: 'https://github.com/login/oauth/authorize'
      AUTH_GITHUB_ACCESS_URL: 'https://github.com/login/oauth/access_token'
      AUTH_GITHUB_PROFILE_URL: 'https://api.github.com/user'
      AUTH_GITHUB_ALLOW_PUBLIC_REGISTRATION: 'true'
      AUTH_GITHUB_SCOPE: 'read:user,user:email'
      AUTH_GITHUB_FIRST_NAME_KEY: 'name'
      AUTH_GITHUB_IDENTIFIER_KEY: 'id'
