version: '3'
services:
  mariadb:
    image: mariadb:10.11.5
    environment:
      - MARIADB_DATABASE=directus
      - MARIADB_USER=directus
      - MARIADB_PASSWORD=password
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    ports:
      - "3306:3306"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
  directus:
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    ports:
      - "8055:8055"
